# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Type',
            new_name='type',
        ),
    ]
