# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20170911_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.IntegerField(choices=[(1, 'Situations'), (2, 'Dialog'), (3, 'Choices'), (4, 'Find the Mistake'), (5, 'Article'), (6, 'Story'), (7, 'Translation'), (8, 'Paragraph')]),
        ),
    ]
