# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20170912_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
