# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Test_Part', to='study.Part'),
        ),
    ]
