# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20170914_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.IntegerField(choices=[(1, 'GENERAL'), (2, 'MCQ')], default=1),
        ),
    ]
